version: '3.9'
services:
  webapp:
    container_name: webapp
    build:
      context: /panemchik-frontend/.
    ports:
      - "3000:3000"
  main:
    container_name: main
    build:
      context: /panemchik-backend/.
    env_file:
        - /panemchik-backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - /panemchik-backend/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "panemchik_Database"
      POSTGRES_USER: "database_user"
      POSTGRES_PASSWORD: "dataPass50$"
    healthcheck:
      test: [“CMD-SHELL”,“pg_isready”]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    restart: always
volumes:
  postgres-volume:

